{
  "formatVersion": "1.1",
  "component": {
    "group": "com.r3.conclave",
    "module": "conclave-common",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.6.1",
      "buildId": "jfwsbwrkhnc75pbni7hruvly54"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.r3.conclave",
          "module": "conclave-mail",
          "version": {
            "requires": "1.0"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "conclave-common-1.0.jar",
          "url": "conclave-common-1.0.jar",
          "size": 2215653,
          "sha512": "edfc4915c7269f8f65810a8bd117ee0e5890e139445d90832d5acffb05bea89f6ed24a5e3da030086c4206d3342f348823d34fa7f4738e257168651c40e01c4d",
          "sha256": "cf63b1c40ef414da8bc0ba6c7b01fde6e016a4c793ea27e736ee9da634e6caac",
          "sha1": "2c338a8e76b6020670055232a391610cb19da4e2",
          "md5": "62843d67ba0dac30f19d2d89c5724ef5"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "net.i2p.crypto",
          "module": "eddsa",
          "version": {
            "requires": "0.3.0"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        },
        {
          "group": "com.r3.conclave",
          "module": "conclave-mail",
          "version": {
            "requires": "1.0"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "conclave-common-1.0.jar",
          "url": "conclave-common-1.0.jar",
          "size": 2215653,
          "sha512": "edfc4915c7269f8f65810a8bd117ee0e5890e139445d90832d5acffb05bea89f6ed24a5e3da030086c4206d3342f348823d34fa7f4738e257168651c40e01c4d",
          "sha256": "cf63b1c40ef414da8bc0ba6c7b01fde6e016a4c793ea27e736ee9da634e6caac",
          "sha1": "2c338a8e76b6020670055232a391610cb19da4e2",
          "md5": "62843d67ba0dac30f19d2d89c5724ef5"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "embedded",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "conclave-common-1.0.jar",
          "url": "conclave-common-1.0.jar",
          "size": 2215653,
          "sha512": "edfc4915c7269f8f65810a8bd117ee0e5890e139445d90832d5acffb05bea89f6ed24a5e3da030086c4206d3342f348823d34fa7f4738e257168651c40e01c4d",
          "sha256": "cf63b1c40ef414da8bc0ba6c7b01fde6e016a4c793ea27e736ee9da634e6caac",
          "sha1": "2c338a8e76b6020670055232a391610cb19da4e2",
          "md5": "62843d67ba0dac30f19d2d89c5724ef5"
        }
      ]
    }
  ]
}
