{
  "formatVersion": "1.1",
  "component": {
    "group": "com.r3.conclave",
    "module": "conclave-mail",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.6.1",
      "buildId": "jfwsbwrkhnc75pbni7hruvly54"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "conclave-mail-1.0.jar",
          "url": "conclave-mail-1.0.jar",
          "size": 1726864,
          "sha512": "8aa5d347ae67ba9e1bebcad5670205ab1fa1437b74a22f2956e0f8fdc67900fd97512c552c01624b284f0ef3ad276ad7618c2ed8b02641cfeeb4a2539153007e",
          "sha256": "a2e2ffda407ae2a7c010c01d2d41845081b99d69c82249d4bacae1ba2abae2dd",
          "sha1": "0497d43c3d0e06d466ec8afdc1ff5b4db51e88db",
          "md5": "d796660ac07f2b2e64bb7dd87cca1ddc"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "conclave-mail-1.0.jar",
          "url": "conclave-mail-1.0.jar",
          "size": 1726864,
          "sha512": "8aa5d347ae67ba9e1bebcad5670205ab1fa1437b74a22f2956e0f8fdc67900fd97512c552c01624b284f0ef3ad276ad7618c2ed8b02641cfeeb4a2539153007e",
          "sha256": "a2e2ffda407ae2a7c010c01d2d41845081b99d69c82249d4bacae1ba2abae2dd",
          "sha1": "0497d43c3d0e06d466ec8afdc1ff5b4db51e88db",
          "md5": "d796660ac07f2b2e64bb7dd87cca1ddc"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "embedded",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "conclave-mail-1.0.jar",
          "url": "conclave-mail-1.0.jar",
          "size": 1726864,
          "sha512": "8aa5d347ae67ba9e1bebcad5670205ab1fa1437b74a22f2956e0f8fdc67900fd97512c552c01624b284f0ef3ad276ad7618c2ed8b02641cfeeb4a2539153007e",
          "sha256": "a2e2ffda407ae2a7c010c01d2d41845081b99d69c82249d4bacae1ba2abae2dd",
          "sha1": "0497d43c3d0e06d466ec8afdc1ff5b4db51e88db",
          "md5": "d796660ac07f2b2e64bb7dd87cca1ddc"
        }
      ]
    }
  ]
}
