{
  "formatVersion": "1.1",
  "component": {
    "group": "com.r3.conclave",
    "module": "conclave-client",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.6.1",
      "buildId": "jfwsbwrkhnc75pbni7hruvly54"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.r3.conclave",
          "module": "conclave-common",
          "version": {
            "requires": "1.0"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "conclave-client-1.0.jar",
          "url": "conclave-client-1.0.jar",
          "size": 11937,
          "sha512": "10e9864997b047dfc618b6c8b9d666ff9c6880068ca9beacfe0c926669c1a83050abec164e19f827eb10c6e01d6345e863b9707ddbb7fe87c9d33cbcd798ee48",
          "sha256": "1fa680b9ff1b6fc0fbec559bb489b5905f97ab6b8a78bb3ae37eb17bfdb0e600",
          "sha1": "fe53650f144d39e19a548bab3deddcf73d71d742",
          "md5": "4ed428671d75097ddb675d1cbd492bb5"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.r3.conclave",
          "module": "conclave-common",
          "version": {
            "requires": "1.0"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "conclave-client-1.0.jar",
          "url": "conclave-client-1.0.jar",
          "size": 11937,
          "sha512": "10e9864997b047dfc618b6c8b9d666ff9c6880068ca9beacfe0c926669c1a83050abec164e19f827eb10c6e01d6345e863b9707ddbb7fe87c9d33cbcd798ee48",
          "sha256": "1fa680b9ff1b6fc0fbec559bb489b5905f97ab6b8a78bb3ae37eb17bfdb0e600",
          "sha1": "fe53650f144d39e19a548bab3deddcf73d71d742",
          "md5": "4ed428671d75097ddb675d1cbd492bb5"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "embedded",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "conclave-client-1.0.jar",
          "url": "conclave-client-1.0.jar",
          "size": 11937,
          "sha512": "10e9864997b047dfc618b6c8b9d666ff9c6880068ca9beacfe0c926669c1a83050abec164e19f827eb10c6e01d6345e863b9707ddbb7fe87c9d33cbcd798ee48",
          "sha256": "1fa680b9ff1b6fc0fbec559bb489b5905f97ab6b8a78bb3ae37eb17bfdb0e600",
          "sha1": "fe53650f144d39e19a548bab3deddcf73d71d742",
          "md5": "4ed428671d75097ddb675d1cbd492bb5"
        }
      ]
    }
  ]
}
