{
  "formatVersion": "1.1",
  "component": {
    "group": "com.r3.conclave",
    "module": "conclave-enclave",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.6.1",
      "buildId": "jfwsbwrkhnc75pbni7hruvly54"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.r3.conclave",
          "module": "conclave-common",
          "version": {
            "requires": "1.0"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "conclave-enclave-1.0.jar",
          "url": "conclave-enclave-1.0.jar",
          "size": 93716,
          "sha512": "c3d4453f5f0e593d7528b788665ffe3d9cf6258a4d18dcb5c60615f269a3ff37fe74b12f1f259c5720c1143626636dd8bde12860de206158eaeb6e5f28986aeb",
          "sha256": "47cfb976dab40be0c6caca38a11197fac2477e204c3c0c06091e0433b26eed15",
          "sha1": "15e05999ca10bab86114d249b08cca005b24aa00",
          "md5": "d5c276fe6fc93435738ea9b908a19940"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.graalvm.sdk",
          "module": "graal-sdk",
          "version": {
            "requires": "20.3.0"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        },
        {
          "group": "com.r3.conclave",
          "module": "filesystem",
          "version": {
            "requires": "1.0"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        },
        {
          "group": "com.r3.conclave",
          "module": "conclave-common",
          "version": {
            "requires": "1.0"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "conclave-enclave-1.0.jar",
          "url": "conclave-enclave-1.0.jar",
          "size": 93716,
          "sha512": "c3d4453f5f0e593d7528b788665ffe3d9cf6258a4d18dcb5c60615f269a3ff37fe74b12f1f259c5720c1143626636dd8bde12860de206158eaeb6e5f28986aeb",
          "sha256": "47cfb976dab40be0c6caca38a11197fac2477e204c3c0c06091e0433b26eed15",
          "sha1": "15e05999ca10bab86114d249b08cca005b24aa00",
          "md5": "d5c276fe6fc93435738ea9b908a19940"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "embedded",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "conclave-enclave-1.0.jar",
          "url": "conclave-enclave-1.0.jar",
          "size": 93716,
          "sha512": "c3d4453f5f0e593d7528b788665ffe3d9cf6258a4d18dcb5c60615f269a3ff37fe74b12f1f259c5720c1143626636dd8bde12860de206158eaeb6e5f28986aeb",
          "sha256": "47cfb976dab40be0c6caca38a11197fac2477e204c3c0c06091e0433b26eed15",
          "sha1": "15e05999ca10bab86114d249b08cca005b24aa00",
          "md5": "d5c276fe6fc93435738ea9b908a19940"
        }
      ]
    }
  ]
}
