{
  "formatVersion": "1.1",
  "component": {
    "group": "com.r3.conclave",
    "module": "native-host-release",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.6.1",
      "buildId": "jfwsbwrkhnc75pbni7hruvly54"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "native-host-release-1.0.jar",
          "url": "native-host-release-1.0.jar",
          "size": 2987183,
          "sha512": "cbb828bcd341c32fed8d4a91f9383b2cac67adf5c26737ef9e63487570b9a66eb0bcda3f955cb206171688b3fa249ee7b27c6025a4867e5ee38241f63366a97d",
          "sha256": "b6f1008311d7a0f2425dbd182f67d906fa0c10a8b3df64cf6c4c780000aeabc5",
          "sha1": "288acf9541fffe890f2d1fd773c7e5469fa33a03",
          "md5": "a6f0acd0ee085d1fdc3c78e9f8c1afa7"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "native-host-release-1.0.jar",
          "url": "native-host-release-1.0.jar",
          "size": 2987183,
          "sha512": "cbb828bcd341c32fed8d4a91f9383b2cac67adf5c26737ef9e63487570b9a66eb0bcda3f955cb206171688b3fa249ee7b27c6025a4867e5ee38241f63366a97d",
          "sha256": "b6f1008311d7a0f2425dbd182f67d906fa0c10a8b3df64cf6c4c780000aeabc5",
          "sha1": "288acf9541fffe890f2d1fd773c7e5469fa33a03",
          "md5": "a6f0acd0ee085d1fdc3c78e9f8c1afa7"
        }
      ]
    }
  ]
}
