{
  "formatVersion": "1.1",
  "component": {
    "group": "com.r3.conclave",
    "module": "native-enclave-debug",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.6.1",
      "buildId": "jfwsbwrkhnc75pbni7hruvly54"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "native-enclave-debug-1.0.jar",
          "url": "native-enclave-debug-1.0.jar",
          "size": 39019367,
          "sha512": "7258afa43f0e4320178fe7bfda6c5b5122b1a3736e5871271ca76573365cc665a6e92688fe74b58ddbe7e31bd2df1f2f7f2a8076a81c5fb15855391f9c4f46ab",
          "sha256": "ff9c84815502826438f4dfb7bc153a3950818fc4c3449db43698de98a93c5dcc",
          "sha1": "2a74b2c3e77c0070aba05c3a784774de966e5215",
          "md5": "00a8c12db618ab40e001ae3b80f297a7"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "native-enclave-debug-1.0.jar",
          "url": "native-enclave-debug-1.0.jar",
          "size": 39019367,
          "sha512": "7258afa43f0e4320178fe7bfda6c5b5122b1a3736e5871271ca76573365cc665a6e92688fe74b58ddbe7e31bd2df1f2f7f2a8076a81c5fb15855391f9c4f46ab",
          "sha256": "ff9c84815502826438f4dfb7bc153a3950818fc4c3449db43698de98a93c5dcc",
          "sha1": "2a74b2c3e77c0070aba05c3a784774de966e5215",
          "md5": "00a8c12db618ab40e001ae3b80f297a7"
        }
      ]
    }
  ]
}
