{
  "formatVersion": "1.1",
  "component": {
    "group": "com.r3.conclave",
    "module": "native-substratevm-debug",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.6.1",
      "buildId": "jfwsbwrkhnc75pbni7hruvly54"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "native-substratevm-debug-1.0.jar",
          "url": "native-substratevm-debug-1.0.jar",
          "size": 881701,
          "sha512": "c357dd5cf2b68e48f43a97fe5341f34674b8f206d60faefa4e88c78e7453a380b38728b6d9a04994e6c4d643edbb0631ff19850e59aa668aaac2173c56990972",
          "sha256": "7603e79bc3b131060f06ee014e518b7f2347499950dd9072d28382a9e8961520",
          "sha1": "78014e5707312fd0525b73669eb154f0ef5ad754",
          "md5": "a111f6dbf05d32d2502213456d42c37f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "native-substratevm-debug-1.0.jar",
          "url": "native-substratevm-debug-1.0.jar",
          "size": 881701,
          "sha512": "c357dd5cf2b68e48f43a97fe5341f34674b8f206d60faefa4e88c78e7453a380b38728b6d9a04994e6c4d643edbb0631ff19850e59aa668aaac2173c56990972",
          "sha256": "7603e79bc3b131060f06ee014e518b7f2347499950dd9072d28382a9e8961520",
          "sha1": "78014e5707312fd0525b73669eb154f0ef5ad754",
          "md5": "a111f6dbf05d32d2502213456d42c37f"
        }
      ]
    }
  ]
}
