{
  "formatVersion": "1.1",
  "component": {
    "group": "com.r3.conclave",
    "module": "native-sign-tool",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.6.1",
      "buildId": "jfwsbwrkhnc75pbni7hruvly54"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "native-sign-tool-1.0.jar",
          "url": "native-sign-tool-1.0.jar",
          "size": 4289823,
          "sha512": "cd40c76272ba691d05b2b6eebb48ce342f5ab49ff5c34869bee268db5c737466341f871dadf6278191439f15135a30fa7c2ec402e322a9b75f7482a7fe2fa7d9",
          "sha256": "859268bdfba3a6edf2877c1356f031938b24426d2369b07cc8f3eb68815ea0d0",
          "sha1": "21a37e03a629e321192f55b53c6dcd5d59cd0390",
          "md5": "a2848838b2d3e177fd9fed392864b557"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "native-sign-tool-1.0.jar",
          "url": "native-sign-tool-1.0.jar",
          "size": 4289823,
          "sha512": "cd40c76272ba691d05b2b6eebb48ce342f5ab49ff5c34869bee268db5c737466341f871dadf6278191439f15135a30fa7c2ec402e322a9b75f7482a7fe2fa7d9",
          "sha256": "859268bdfba3a6edf2877c1356f031938b24426d2369b07cc8f3eb68815ea0d0",
          "sha1": "21a37e03a629e321192f55b53c6dcd5d59cd0390",
          "md5": "a2848838b2d3e177fd9fed392864b557"
        }
      ]
    }
  ]
}
