{
  "formatVersion": "1.1",
  "component": {
    "group": "com.r3.conclave",
    "module": "conclave-host",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.6.1",
      "buildId": "jfwsbwrkhnc75pbni7hruvly54"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.r3.conclave",
          "module": "conclave-common",
          "version": {
            "requires": "1.0"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "conclave-host-1.0.jar",
          "url": "conclave-host-1.0.jar",
          "size": 94292,
          "sha512": "7f84ceaefba28a792a4d70a3686400a3d996fdc4eab45ee763af6354162d61cd4048136280a1f2a88208fefdcb37213dfe28f75abc1216a4037c5e5327a24679",
          "sha256": "43992f675942601265f5f1735857d607238707f4d19758eea0d5c69d221aa72f",
          "sha1": "0aa92806565a998614b71990f90496364a141a06",
          "md5": "f58d82a37b5eeef9f5908156110dc48a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "io.github.classgraph",
          "module": "classgraph",
          "version": {
            "requires": "4.8.69"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.26"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        },
        {
          "group": "com.r3.conclave",
          "module": "conclave-common",
          "version": {
            "requires": "1.0"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        },
        {
          "group": "com.r3.conclave",
          "module": "native-host-release",
          "version": {
            "requires": "1.0"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        },
        {
          "group": "com.r3.conclave",
          "module": "native-host-debug",
          "version": {
            "requires": "1.0"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        },
        {
          "group": "com.r3.conclave",
          "module": "native-host-simulation",
          "version": {
            "requires": "1.0"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        },
        {
          "group": "com.r3.conclave",
          "module": "native-host-shared",
          "version": {
            "requires": "1.0"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "conclave-host-1.0.jar",
          "url": "conclave-host-1.0.jar",
          "size": 94292,
          "sha512": "7f84ceaefba28a792a4d70a3686400a3d996fdc4eab45ee763af6354162d61cd4048136280a1f2a88208fefdcb37213dfe28f75abc1216a4037c5e5327a24679",
          "sha256": "43992f675942601265f5f1735857d607238707f4d19758eea0d5c69d221aa72f",
          "sha1": "0aa92806565a998614b71990f90496364a141a06",
          "md5": "f58d82a37b5eeef9f5908156110dc48a"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "embedded",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "conclave-host-1.0.jar",
          "url": "conclave-host-1.0.jar",
          "size": 94292,
          "sha512": "7f84ceaefba28a792a4d70a3686400a3d996fdc4eab45ee763af6354162d61cd4048136280a1f2a88208fefdcb37213dfe28f75abc1216a4037c5e5327a24679",
          "sha256": "43992f675942601265f5f1735857d607238707f4d19758eea0d5c69d221aa72f",
          "sha1": "0aa92806565a998614b71990f90496364a141a06",
          "md5": "f58d82a37b5eeef9f5908156110dc48a"
        }
      ]
    }
  ]
}
