{
  "formatVersion": "1.1",
  "component": {
    "group": "com.r3.conclave",
    "module": "macos-sign-tool",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.6.1",
      "buildId": "jfwsbwrkhnc75pbni7hruvly54"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "macos-sign-tool-1.0.jar",
          "url": "macos-sign-tool-1.0.jar",
          "size": 1166370,
          "sha512": "ab72ca0e89230dc6799b7d698b93cf73882423394e0fb2cfbce97c441f64a76a26e3c9524ffa4ea2ba723d9e54430d8506069e9fc0eeb283137f88410ca92565",
          "sha256": "a38e8caddc04fb4c4d92449c1d77be1b14fa9446b5104381493f733300f8e205",
          "sha1": "e61ab5d1917a3b536d68f975e71e28c5a462b99a",
          "md5": "973dbc88f9cc6baed788cba0d1502c7e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "macos-sign-tool-1.0.jar",
          "url": "macos-sign-tool-1.0.jar",
          "size": 1166370,
          "sha512": "ab72ca0e89230dc6799b7d698b93cf73882423394e0fb2cfbce97c441f64a76a26e3c9524ffa4ea2ba723d9e54430d8506069e9fc0eeb283137f88410ca92565",
          "sha256": "a38e8caddc04fb4c4d92449c1d77be1b14fa9446b5104381493f733300f8e205",
          "sha1": "e61ab5d1917a3b536d68f975e71e28c5a462b99a",
          "md5": "973dbc88f9cc6baed788cba0d1502c7e"
        }
      ]
    }
  ]
}
