{
  "formatVersion": "1.1",
  "component": {
    "group": "com.r3.conclave",
    "module": "plugin-enclave-gradle",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.6.1",
      "buildId": "jfwsbwrkhnc75pbni7hruvly54"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "plugin-enclave-gradle-1.0.jar",
          "url": "plugin-enclave-gradle-1.0.jar",
          "size": 112913,
          "sha512": "8755c9ba98abd578887a7f7a8d81650272688ac4ee1ba756e3dc7856b08b9c08a6284d619d44862072fad1136200835b8370a5b5fe34daaf6ac3f2e585f64c96",
          "sha256": "228753b132d10d69c464f625cf1f757933d387f1ec2b7546b57902ee85c9ae53",
          "sha1": "125ed6269c67573703e6c0e037264925f266202e",
          "md5": "f46fbaa23501df9ff38e6a321e74d461"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.r3.conclave",
          "module": "conclave-testing",
          "version": {
            "requires": "1.0"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        },
        {
          "group": "com.github.jengelman.gradle.plugins",
          "module": "shadow",
          "version": {
            "requires": "5.2.0"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        },
        {
          "group": "io.github.classgraph",
          "module": "classgraph",
          "version": {
            "requires": "4.8.69"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        },
        {
          "group": "org.bouncycastle",
          "module": "bcpkix-jdk15on",
          "version": {
            "requires": "1.66"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "plugin-enclave-gradle-1.0.jar",
          "url": "plugin-enclave-gradle-1.0.jar",
          "size": 112913,
          "sha512": "8755c9ba98abd578887a7f7a8d81650272688ac4ee1ba756e3dc7856b08b9c08a6284d619d44862072fad1136200835b8370a5b5fe34daaf6ac3f2e585f64c96",
          "sha256": "228753b132d10d69c464f625cf1f757933d387f1ec2b7546b57902ee85c9ae53",
          "sha1": "125ed6269c67573703e6c0e037264925f266202e",
          "md5": "f46fbaa23501df9ff38e6a321e74d461"
        }
      ]
    }
  ]
}
