{
  "formatVersion": "1.1",
  "component": {
    "group": "com.r3.conclave",
    "module": "native-binutils",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.6.1",
      "buildId": "jfwsbwrkhnc75pbni7hruvly54"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "native-binutils-1.0.jar",
          "url": "native-binutils-1.0.jar",
          "size": 7723907,
          "sha512": "09bd61ff4e46c8fa7034902c71004e9dbef6d0ac2d7d65bc93a1ce4d0e4c4c6348826dc839e9f6fb0b5aa0fd6d0275c1517eb7ea7d427011dc7afffb6091c404",
          "sha256": "238d1341e6a7e480792c766f3cf531478fdef37b4a920e695116053b291867d1",
          "sha1": "4e7df41d35ed9b8163038aa93ad684ce499d3fe5",
          "md5": "34f6fd2a178282034d05d0d37a77f7fe"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "native-binutils-1.0.jar",
          "url": "native-binutils-1.0.jar",
          "size": 7723907,
          "sha512": "09bd61ff4e46c8fa7034902c71004e9dbef6d0ac2d7d65bc93a1ce4d0e4c4c6348826dc839e9f6fb0b5aa0fd6d0275c1517eb7ea7d427011dc7afffb6091c404",
          "sha256": "238d1341e6a7e480792c766f3cf531478fdef37b4a920e695116053b291867d1",
          "sha1": "4e7df41d35ed9b8163038aa93ad684ce499d3fe5",
          "md5": "34f6fd2a178282034d05d0d37a77f7fe"
        }
      ]
    }
  ]
}
