{
  "formatVersion": "1.1",
  "component": {
    "group": "com.r3.conclave",
    "module": "graal",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.6.1",
      "buildId": "jfwsbwrkhnc75pbni7hruvly54"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "graal-1.0.jar",
          "url": "graal-1.0.jar",
          "size": 93682581,
          "sha512": "fdd54052e2ca658e476ca0dda1ba064b3f86e2ce079e808ed4c24a8f755978168e03465bba36454d9350b330d7bb7ff10f3c277a4865ecfba73c4ce5fd6614b4",
          "sha256": "26a17bad3ca03ac33664f7b4659e669e15d3130dff7cb34d28b006f48c0bd154",
          "sha1": "214fe5b89d04756aff9db4819d5a67135215ce0e",
          "md5": "c2c4a2fa021f42223f2b691ba55ec33a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "graal-1.0.jar",
          "url": "graal-1.0.jar",
          "size": 93682581,
          "sha512": "fdd54052e2ca658e476ca0dda1ba064b3f86e2ce079e808ed4c24a8f755978168e03465bba36454d9350b330d7bb7ff10f3c277a4865ecfba73c4ce5fd6614b4",
          "sha256": "26a17bad3ca03ac33664f7b4659e669e15d3130dff7cb34d28b006f48c0bd154",
          "sha1": "214fe5b89d04756aff9db4819d5a67135215ce0e",
          "md5": "c2c4a2fa021f42223f2b691ba55ec33a"
        }
      ]
    }
  ]
}
