{
  "formatVersion": "1.1",
  "component": {
    "group": "com.r3.conclave",
    "module": "native-substratevm-release",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.6.1",
      "buildId": "jfwsbwrkhnc75pbni7hruvly54"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "native-substratevm-release-1.0.jar",
          "url": "native-substratevm-release-1.0.jar",
          "size": 133582,
          "sha512": "990800d9c9ffcc626e12e097c4add9458ac8225ccf556f08d7dd4f7326d43788120c9c38326f94c91b8456257caedf22c4e73980b9c8bd75c7b88ab9837dbf5e",
          "sha256": "f71a83f9ec43b57a3640d159dda4775d52f996b7ca63203aa5face72a234bce6",
          "sha1": "642e570700f1b1ac478c8f3b0186e66559831108",
          "md5": "fb046d465afcadcdc26a77032538fb5d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "native-substratevm-release-1.0.jar",
          "url": "native-substratevm-release-1.0.jar",
          "size": 133582,
          "sha512": "990800d9c9ffcc626e12e097c4add9458ac8225ccf556f08d7dd4f7326d43788120c9c38326f94c91b8456257caedf22c4e73980b9c8bd75c7b88ab9837dbf5e",
          "sha256": "f71a83f9ec43b57a3640d159dda4775d52f996b7ca63203aa5face72a234bce6",
          "sha1": "642e570700f1b1ac478c8f3b0186e66559831108",
          "md5": "fb046d465afcadcdc26a77032538fb5d"
        }
      ]
    }
  ]
}
