{
  "formatVersion": "1.1",
  "component": {
    "group": "com.r3.conclave",
    "module": "filesystem",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.6.1",
      "buildId": "jfwsbwrkhnc75pbni7hruvly54"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "filesystem-1.0.jar",
          "url": "filesystem-1.0.jar",
          "size": 13300245,
          "sha512": "843141ebf08adadfd0fd53624c4090a6b0c8e1fef156e8cdd0214134f97a9c3cd9c0d96af8d0694a956c89b8adb08c9864182a2e35c5c089865208595ebde3db",
          "sha256": "c1b19a539a893a7cc59afabdd44fdc5ad79f2b4dd853c76f6a9e70aae20445a8",
          "sha1": "ed133c97bb3f7c45f99f70f9221985d1331cc9a3",
          "md5": "d733f65e220d206e7815ceea7da823a5"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "29.0-jre"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        },
        {
          "group": "com.ibm.icu",
          "module": "icu4j",
          "version": {
            "requires": "51.2"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        },
        {
          "group": "com.google.auto.service",
          "module": "auto-service",
          "version": {
            "requires": "1.0-rc2"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        },
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "2.0.1"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "filesystem-1.0.jar",
          "url": "filesystem-1.0.jar",
          "size": 13300245,
          "sha512": "843141ebf08adadfd0fd53624c4090a6b0c8e1fef156e8cdd0214134f97a9c3cd9c0d96af8d0694a956c89b8adb08c9864182a2e35c5c089865208595ebde3db",
          "sha256": "c1b19a539a893a7cc59afabdd44fdc5ad79f2b4dd853c76f6a9e70aae20445a8",
          "sha1": "ed133c97bb3f7c45f99f70f9221985d1331cc9a3",
          "md5": "d733f65e220d206e7815ceea7da823a5"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "embedded",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "filesystem-1.0.jar",
          "url": "filesystem-1.0.jar",
          "size": 13300245,
          "sha512": "843141ebf08adadfd0fd53624c4090a6b0c8e1fef156e8cdd0214134f97a9c3cd9c0d96af8d0694a956c89b8adb08c9864182a2e35c5c089865208595ebde3db",
          "sha256": "c1b19a539a893a7cc59afabdd44fdc5ad79f2b4dd853c76f6a9e70aae20445a8",
          "sha1": "ed133c97bb3f7c45f99f70f9221985d1331cc9a3",
          "md5": "d733f65e220d206e7815ceea7da823a5"
        }
      ]
    }
  ]
}
