{
  "formatVersion": "1.1",
  "component": {
    "group": "com.r3.conclave",
    "module": "native-substratevm-simulation",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.6.1",
      "buildId": "jfwsbwrkhnc75pbni7hruvly54"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "native-substratevm-simulation-1.0.jar",
          "url": "native-substratevm-simulation-1.0.jar",
          "size": 882463,
          "sha512": "8cb11ff7fa55ea64cc81ec65a2008756dc66b47df7264e82755e00d2235b2ec1b351257cfa2aa7711a68b732a89e6afa5dc92d4a7714e018f65923e820b3b92b",
          "sha256": "4bce7c5a08dce30028941b6af9e7b560530840f95ffce326a333af6de556e522",
          "sha1": "d38dff981e010713aff94b52a0fcd456e7989fea",
          "md5": "719ad106096206fb76d7a9dedd7c0b1c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "native-substratevm-simulation-1.0.jar",
          "url": "native-substratevm-simulation-1.0.jar",
          "size": 882463,
          "sha512": "8cb11ff7fa55ea64cc81ec65a2008756dc66b47df7264e82755e00d2235b2ec1b351257cfa2aa7711a68b732a89e6afa5dc92d4a7714e018f65923e820b3b92b",
          "sha256": "4bce7c5a08dce30028941b6af9e7b560530840f95ffce326a333af6de556e522",
          "sha1": "d38dff981e010713aff94b52a0fcd456e7989fea",
          "md5": "719ad106096206fb76d7a9dedd7c0b1c"
        }
      ]
    }
  ]
}
